In [1]:
"""NumPy stands for Numerical Python, is an open-source Python library that
   provides support for large, multi-dimensional arrays and matrices."""

"""numpy.ndarray is a data structure, a multidimensional array that allows the storage and manipulation of numerical data
NumPy contains many functions that allow operations to be performed element-wise on arrays.
NumPy supports linear algebra such as matrix multiplication, eigenvalue decomposition, and solving linear equations."""

'numpy.ndarray is a data structure, a multidimensional array that allows the storage and manipulation of numerical data\nNumPy contains many functions that allow operations to be performed element-wise on arrays.\nNumPy supports linear algebra such as matrix multiplication, eigenvalue decomposition, and solving linear equations.'

In [2]:
import numpy as np

In [3]:


arr=np.array([[1,2,3,4],
              [5,6,7,8]])



print("array type:",type(arr))

print("array dimensions:",arr.ndim)

print(arr)

print("array shape:",arr.shape)

print("array size:",arr.size)

print("elements data type:",arr.dtype)

array type: <class 'numpy.ndarray'>
array dimensions: 2
[[1 2 3 4]
 [5 6 7 8]]
array shape: (2, 4)
array size: 8
elements data type: int64


In [4]:
arr=np.array((1,2,3))
print("array created with tuple")
#by tuple we can create only 1*n dimensional array only
print("elements data type:",arr.dtype)
print(arr)
print("array created with list")
arr1=np.array([[1,2,3],[4,5,6]],dtype='float')
print("elements data type:",arr1.dtype)
print(arr1)

array created with tuple
elements data type: int64
[1 2 3]
array created with list
elements data type: float64
[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
print("array with all zeroes")
arr=np.zeros((3,4))

print(arr)
print("datatype:",arr.dtype)
print("size:",arr.size)
print("shape:",arr.shape)

print("array with ones")
arr1=np.ones((3,4))
print(arr1)

print("array with other numbers")
arr2=np.full((3,4),5,dtype='float')
print(arr2)
print("datatype:",arr2.dtype)

print("array with random numbers:")
arr3=np.random.random((3,4))
print(arr3)
print("datatype:",arr3.dtype)

array with all zeroes
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
datatype: float64
size: 12
shape: (3, 4)
array with ones
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array with other numbers
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
datatype: float64
array with random numbers:
[[0.83465949 0.98586481 0.60714082 0.16205027]
 [0.06447387 0.34150256 0.15495737 0.76327829]
 [0.02486708 0.20831212 0.97455607 0.40327067]]
datatype: float64


In [6]:
#slicing
#[start:end:step]

arr=np.array([[1,2,3,4],[5,6,7,8],[9,3,5,4]])

print(arr[:2])
print("\n")
print(arr[1,1:4])
print("\n")
print(arr[0:3,0:3])
print("\n")
print(arr[0:3,2])
print("\n")
print(arr[:2,::2])
temp=arr[[0,1,2],[2,1,0]]
print ("\nElements at indices (0, 2), (1, 1), (2, 0):\n", temp)

[[1 2 3 4]
 [5 6 7 8]]


[6 7 8]


[[1 2 3]
 [5 6 7]
 [9 3 5]]


[3 7 5]


[[1 3]
 [5 7]]

Elements at indices (0, 2), (1, 1), (2, 0):
 [3 6 9]


In [7]:
#reshaping
#3*3=2*2*3
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 10, 9]])

new_arr=arr.reshape(2,2,3)
print("original arr:\n",arr)
print("reshaped arr:\n",new_arr)

original arr:
 [[ 1  2  3  4]
 [ 5  2  4  2]
 [ 1  2 10  9]]
reshaped arr:
 [[[ 1  2  3]
  [ 4  5  2]]

 [[ 4  2  1]
  [ 2 10  9]]]


In [8]:
#flatten

arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
flat=arr.flatten()
print("original arr:\n",arr)
print("reshaped arr:\n",flat)

original arr:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
reshaped arr:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [9]:
#arithmetic operations
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
print(arr+1)
print(arr-2)
print(arr*2)
print("transpose of array:")
print(arr.T)

[[2 3 4 5]
 [6 3 5 3]
 [2 3 1 2]]
[[-1  0  1  2]
 [ 3  0  2  0]
 [-1  0 -2 -1]]
[[ 2  4  6  8]
 [10  4  8  4]
 [ 2  4  0  2]]
transpose of array:
[[1 5 1]
 [2 2 2]
 [3 4 0]
 [4 2 1]]


In [10]:
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
print("largest element of array:",arr.max())
print("smallest element of array:",arr.min())
print("row wiselargest element of array:",arr.max(axis=1))
print("column wise smallest element of array:",arr.min(axis=0))
print("sum of all array elements:",arr.sum())
print("cummulative sum along each row:",arr.cumsum(axis=1))

largest element of array: 5
smallest element of array: 0
row wiselargest element of array: [4 5 2]
column wise smallest element of array: [1 2 0 1]
sum of all array elements: 27
cummulative sum along each row: [[ 1  3  6 10]
 [ 5  7 11 13]
 [ 1  3  3  4]]


In [11]:
a=np.array([[1,2],[5,6]])
b=np.array([[2,5],[0,1]])
print("sum of 2 arrays:\n",a+b)
print("sub of 2 arrays:\n",a-b)
print("multiply element wise of 2 arrays:\n",a*b)
print("matrix multiplication of 2 arrays:\n",a.dot(b))

sum of 2 arrays:
 [[3 7]
 [5 7]]
sub of 2 arrays:
 [[-1 -3]
 [ 5  5]]
multiply element wise of 2 arrays:
 [[ 2 10]
 [ 0  6]]
matrix multiplication of 2 arrays:
 [[ 2  7]
 [10 31]]


In [12]:
arr=np.array([1,4,6,9])
print("exponent of array:\n",np.exp(arr))
print("sqrt of array:\n",np.sqrt(arr))

exponent of array:
 [2.71828183e+00 5.45981500e+01 4.03428793e+02 8.10308393e+03]
sqrt of array:
 [1.         2.         2.44948974 3.        ]


In [13]:
#sorting
arr = np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1, 2, 0, 1]])
print("sorted array:\n",np.sort(arr,axis=None))
print("row wise sorted array:\n",np.sort(arr,axis=1))
print("column wise sorted array:\n",np.sort(arr,axis=0))
print("colums wise sorted array using merge sort:\n",np.sort(arr,axis=0,kind='mergesort'))

sorted array:
 [0 1 1 1 2 2 2 2 3 4 4 5]
row wise sorted array:
 [[1 2 3 4]
 [2 2 4 5]
 [0 1 1 2]]
column wise sorted array:
 [[1 2 0 1]
 [1 2 3 2]
 [5 2 4 4]]
colums wise sorted array using merge sort:
 [[1 2 0 1]
 [1 2 3 2]
 [5 2 4 4]]


In [14]:
# Example to show sorting of structured array
# set alias names for dtypes

dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
#s10 here means string with maxlength 10
# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('balaji', 2008, 8.7), 
           ('yagna', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr=np.array(values,dtype=dtypes)
print ("\nArray sorted by names:\n",np.sort(arr,order='name'))
print ("\nArray sorted by names:\n",np.sort(arr,order=['cgpa','grad_year']))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Hrithik', 2009, 8.5) (b'balaji', 2008, 8.7)
 (b'yagna', 2008, 7.9)]

Array sorted by names:
 [(b'yagna', 2008, 7.9) (b'Hrithik', 2009, 8.5) (b'balaji', 2008, 8.7)
 (b'Aakash', 2009, 9. )]
