# Introduction to NumPy

NumPy is a fundamental package for scientific computing in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures efficiently. In this notebook, we'll explore some of the core features and methods of NumPy.

## Installation

If you haven't installed NumPy yet, you can do so using pip:

```bash
pip install numpy


In [1]:
import numpy as np

In [2]:
import numpy as np

# From a list
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

# From a tuple
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)


[1 2 3 4 5]
[1 2 3 4 5]


In [3]:
# Creating an array of zeros
zeros_array = np.zeros((3, 4))
print("Zeros Array:\n", zeros_array)

# Creating an array of ones
ones_array = np.ones((2, 3))
print("Ones Array:\n", ones_array)

# Creating an array filled with a specific value
full_array = np.full((2, 2), 7)
print("Full Array:\n", full_array)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]


In [4]:
# Array with a range of values
range_array = np.arange(0, 10, 2)
print("Range Array:\n", range_array)

# Array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:\n", linspace_array)


Range Array:
 [0 2 4 6 8]
Linspace Array:
 [0.   0.25 0.5  0.75 1.  ]


In [5]:
# Example array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Shape
print("Shape:", array.shape)

# Dimensions
print("Number of Dimensions:", array.ndim)

# Size
print("Total Number of Elements:", array.size)

# Data Type
print("Data Type:", array.dtype)


Shape: (2, 3)
Number of Dimensions: 2
Total Number of Elements: 6
Data Type: int64


In [6]:
# Element-wise operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Addition
sum_array = array1 + array2
print("Sum Array:", sum_array)

# Multiplication
product_array = array1 * array2
print("Product Array:", product_array)

# Broadcasting
array3 = np.array([[1], [2], [3]])
broadcasted_array = array3 + np.array([10, 20, 30])
print("Broadcasted Array:\n", broadcasted_array)


Sum Array: [5 7 9]
Product Array: [ 4 10 18]
Broadcasted Array:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [7]:
# Example array
array = np.array([1, 2, 3, 4, 5])

# Sum
print("Sum:", np.sum(array))

# Mean
print("Mean:", np.mean(array))

# Standard Deviation
print("Standard Deviation:", np.std(array))


Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


In [8]:
# Example array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing an element
element = array[1, 2]
print("Element at position (1, 2):", element)

# Slicing
slice_array = array[0:2, 1:3]
print("Sliced Array:\n", slice_array)


Element at position (1, 2): 6
Sliced Array:
 [[2 3]
 [5 6]]


In [9]:
# Example array
array = np.array([1, 2, 3, 4, 5])

# Square root
sqrt_array = np.sqrt(array)
print("Square Root Array:", sqrt_array)

# Exponential
exp_array = np.exp(array)
print("Exponential Array:", exp_array)

# Trigonometric functions
sin_array = np.sin(array)
print("Sine Array:", sin_array)


Square Root Array: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential Array: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine Array: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [10]:
# Example matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
product_matrix = np.matmul(matrix_a, matrix_b)
print("Matrix Product:\n", product_matrix)

# Determinant
determinant = np.linalg.det(matrix_a)
print("Determinant:", determinant)


Matrix Product:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004


In [11]:
# Random integers
rand_integers = np.random.randint(0, 10, size=(3, 3))
print("Random Integers Array:\n", rand_integers)

# Random floats
rand_floats = np.random.rand(3, 3)
print("Random Floats Array:\n", rand_floats)

# Normal distribution
normal_dist = np.random.randn(3, 3)
print("Normal Distribution Array:\n", normal_dist)


Random Integers Array:
 [[0 5 5]
 [6 3 9]
 [0 0 6]]
Random Floats Array:
 [[0.03482069 0.63452073 0.74445767]
 [0.34084384 0.47052589 0.38391158]
 [0.70513163 0.38612648 0.46310183]]
Normal Distribution Array:
 [[-0.15701946 -1.26294739  1.64175884]
 [-0.97885166  0.83026245 -0.33026098]
 [-0.69028911  0.08192298  2.55450251]]
